# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'MoEngageiOSCocoaSampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MoEngage-iOS-SDK', '9.20.1'
  pod 'MoEngage-iOS-SDK/InApps'
  pod 'MoEngage-iOS-SDK/Cards'
  pod 'MoEngage-iOS-SDK/GeoFence'
  pod 'MoEngage-iOS-SDK/RichNotification'
  pod 'MoEngage-iOS-SDK/Inbox'
  pod 'MoEngage-iOS-SDK/RealTimeTrigger'
end
